services:
  - type: worker
    name: guardianbot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: BOT_NAME
        value: GuardianBot
      - key: WARN_LIMIT
        value: "3"
    autoDeploy: true
